### ISSUE TITLE
InvalidTemplate - publicIPAddressesTemplate

### ISSUE THREAD

**Issue by wyliegraham** [mspnp/identity-reference-architectures#12]
deployment of adds-extend-domain fails with this issue:

{'additionalProperties': {}, 'code': 'InvalidTemplate', 'message': "Deployment template validation failed: 'The template variable 'publicIPAddressesTemplate' is not valid: The language expression property 'templateLink' doesn't exist, available properties are 'template, templateHash, parameters, mode, provisioningState'.. Please see https://aka.ms/arm-template-expressions for usage details.'.", 'target': None, 'details': None, 'additionalInfo': [{'additionalProperties': {}, 'type': 'TemplateViolation', 'info': {'lineNumber': 24, 'linePosition': 193, 'path': 'properties.template.variables.publicIPAddressesTemplate'}}]}

**Comment by ferantivero** [comment]
thanks for reporting this @wyliegraham, it seems to be an upstream issue with az cli and they are currently working on it. 

For more information please let's take a look at Azure/azure-cli#12990 or Azure/azure-cli#12890

**Comment by ferantivero** [comment]
@wyliegraham a [new version of az cli](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.6.0) has been release and with that the fix for this issue. 

Please let me close this issue for now, and feel free to re-open this or create new issues if more support is needed.
