### ISSUE TITLE
vm list buffer

### ISSUE THREAD

**Issue by gvnshtn** [mspnp/identity-reference-architectures#14]
https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-forest#prerequisites
I install the Azure building blocks and run the command to deploy the datacentre.
I'm hitting the buffer size issue, so follow the steps from the issue logged here
https://github.com/mspnp/identity-reference-architectures/issues/11#issuecomment-624039529
Still no success, screen attached:

<img width="919" alt="buffer" src="https://user-images.githubusercontent.com/8502046/101719081-7fe4ae80-3a9a-11eb-880a-9efefbd0bd6f.png">

**Comment by magrande** [comment]
Thank you for raising this issue. I just got a repro today, using the latest version of azbb and what worked for me was to manually edit the azCLI.js file located here :


C:\Users\[you user]\AppData\Roaming\npm\node_modules\@mspnp\azure-building-blocks\src

And add the masBuffer setting:

 spawnOptions = spawnOptions || {
        stdio: 'pipe',
        shell: true,
        **maxBuffer: 1024 * 1024 * 20**
    };


Let me know if it works on your end.

Thanks you.

**Comment by magrande** [comment]
Please let us close this for now. If the proposed solution doesn't work for you, please feel free to re-open it.
