### ISSUE TITLE
Refresh Token has expired due to Inactivity

### ISSUE THREAD

**Issue by sumitsancheti** [mspnp/identity-reference-architectures#9]
Getting following error while running onprem.json part of "adds-extend-domain" folder - 

Error:

> AADSTS700082: The refresh token has expired due to 
inactivity.ï¿½The token was issued on 2019-01-28T08:58:16.7135740Z and was inactive for 90.00:00:00.\r\nTrace ID: 
624f7355-f654-4e51-bf41-417b1c4b6200\r\nCorrelation ID: 06fd79c9-fe43-4f61-bb6f-22df21f2c597\r\nTimestamp: 
2019-09-27 04:38:50Z","error_codes":[700082],"timestamp":"2019-09-27 04:38:50Z","trace_id":"624f7355-f654-4e51-bf4
1-417b1c4b6200","correlation_id":"06fd79c9-fe43-4f61-bb6f-22df21f2c597","error_uri":"https://login.microsoftonline
.com/error?code=700082"}

**Comment by magrande** [comment]
I'm sorry to hear you ran into an issue when deploying one of our Identity reference architectures. At first glance it looks like you had an old set of credentials (token was issued on January 2019) and you tried to use it eight month later. Refresh tokens have a life time of 90 days. I am going to close this issue for now. Please, feel free to re open it if you keep getting this error.
